language:  generic

notifications:
  slack:
    rooms:
      - nozeio:LIFY1Jtkx0FRcLq3u1WliHRZ

matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.0.3-release/ubuntu1404/swift-4.0.3-RELEASE/swift-4.0.3-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.1.2-release/ubuntu1404/swift-4.1.2-RELEASE/swift-4.1.2-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.2.4-release/ubuntu1404/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-5.0-release/ubuntu1404/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   osx
          osx_image: xcode8.3
        - os:   osx
          osx_image: xcode9
        - os:   osx
          osx_image: xcode9.2
        - os:   osx
          osx_image: xcode9.3

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - swift build -c release
    - swift build -c debug
